service:
    name: sls-graphql

plugins:
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs8.10

functions:
    hello:
        handler: src/graphql.hello
        events:
            - http:
                  method: get
                  path: hello
